language: node_js
node_js:
  - stable
  - '5.1'
  - '5'
  - '4.2'
  - '4.1'
  - '4.0'
after_script:
  - npm run coveralls

# Google Chrome
#
# https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
# http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr
# http://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
